/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalTrades' : bigint,
  'avgRR' : number,
  'wins' : bigint,
  'exitedEarlyPercent' : number,
  'losses' : bigint,
  'totalNetR' : number,
  'movedStopLossPercent' : number,
  'breakEvens' : bigint,
  'avgRMultiple' : number,
  'expectancy' : number,
  'winRate' : number,
  'followedRulesPercent' : number,
  'profitFactor' : number,
}
export type ExternalBlob = Uint8Array;
export interface Trade {
  'id' : string,
  'result' : string,
  'direction' : string,
  'timeframe' : string,
  'pnlPercent' : number,
  'riskPercent' : number,
  'owner' : Principal,
  'date' : string,
  'psychAfter' : Array<string>,
  'psychBefore' : Array<string>,
  'takeProfit' : number,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'movedStopLoss' : boolean,
  'psychDuring' : Array<string>,
  'entryReason' : string,
  'rMultiple' : number,
  'setupGrade' : string,
  'updatedAt' : bigint,
  'rrRatio' : number,
  'session' : string,
  'stopLoss' : number,
  'setupType' : string,
  'entryPrice' : number,
  'biasBeforeEntry' : string,
  'followedRules' : boolean,
  'exitedEarly' : boolean,
  'screenshot' : [] | [ExternalBlob],
  'symbol' : string,
  'mainLesson' : string,
}
export interface TradeInput {
  'result' : string,
  'direction' : string,
  'timeframe' : string,
  'pnlPercent' : number,
  'riskPercent' : number,
  'date' : string,
  'psychAfter' : Array<string>,
  'psychBefore' : Array<string>,
  'takeProfit' : number,
  'tags' : Array<string>,
  'movedStopLoss' : boolean,
  'psychDuring' : Array<string>,
  'entryReason' : string,
  'rMultiple' : number,
  'setupGrade' : string,
  'rrRatio' : number,
  'session' : string,
  'stopLoss' : number,
  'setupType' : string,
  'entryPrice' : number,
  'biasBeforeEntry' : string,
  'followedRules' : boolean,
  'exitedEarly' : boolean,
  'screenshot' : [] | [ExternalBlob],
  'symbol' : string,
  'mainLesson' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTrade' : ActorMethod<[TradeInput], Trade>,
  'deleteTrade' : ActorMethod<[string], boolean>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTradeById' : ActorMethod<[string], [] | [Trade]>,
  'getTrades' : ActorMethod<[], Array<Trade>>,
  'getUniqueTags' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTrade' : ActorMethod<[string, TradeInput], [] | [Trade]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];