/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TradeInput = IDL.Record({
  'result' : IDL.Text,
  'direction' : IDL.Text,
  'timeframe' : IDL.Text,
  'pnlPercent' : IDL.Float64,
  'riskPercent' : IDL.Float64,
  'date' : IDL.Text,
  'psychAfter' : IDL.Vec(IDL.Text),
  'psychBefore' : IDL.Vec(IDL.Text),
  'takeProfit' : IDL.Float64,
  'tags' : IDL.Vec(IDL.Text),
  'movedStopLoss' : IDL.Bool,
  'psychDuring' : IDL.Vec(IDL.Text),
  'entryReason' : IDL.Text,
  'rMultiple' : IDL.Float64,
  'setupGrade' : IDL.Text,
  'rrRatio' : IDL.Float64,
  'session' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'setupType' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'biasBeforeEntry' : IDL.Text,
  'followedRules' : IDL.Bool,
  'exitedEarly' : IDL.Bool,
  'screenshot' : IDL.Opt(ExternalBlob),
  'symbol' : IDL.Text,
  'mainLesson' : IDL.Text,
});
export const Trade = IDL.Record({
  'id' : IDL.Text,
  'result' : IDL.Text,
  'direction' : IDL.Text,
  'timeframe' : IDL.Text,
  'pnlPercent' : IDL.Float64,
  'riskPercent' : IDL.Float64,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'psychAfter' : IDL.Vec(IDL.Text),
  'psychBefore' : IDL.Vec(IDL.Text),
  'takeProfit' : IDL.Float64,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'movedStopLoss' : IDL.Bool,
  'psychDuring' : IDL.Vec(IDL.Text),
  'entryReason' : IDL.Text,
  'rMultiple' : IDL.Float64,
  'setupGrade' : IDL.Text,
  'updatedAt' : IDL.Int,
  'rrRatio' : IDL.Float64,
  'session' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'setupType' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'biasBeforeEntry' : IDL.Text,
  'followedRules' : IDL.Bool,
  'exitedEarly' : IDL.Bool,
  'screenshot' : IDL.Opt(ExternalBlob),
  'symbol' : IDL.Text,
  'mainLesson' : IDL.Text,
});
export const Analytics = IDL.Record({
  'totalTrades' : IDL.Nat,
  'avgRR' : IDL.Float64,
  'wins' : IDL.Nat,
  'exitedEarlyPercent' : IDL.Float64,
  'losses' : IDL.Nat,
  'totalNetR' : IDL.Float64,
  'movedStopLossPercent' : IDL.Float64,
  'breakEvens' : IDL.Nat,
  'avgRMultiple' : IDL.Float64,
  'expectancy' : IDL.Float64,
  'winRate' : IDL.Float64,
  'followedRulesPercent' : IDL.Float64,
  'profitFactor' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTrade' : IDL.Func([TradeInput], [Trade], []),
  'deleteTrade' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTradeById' : IDL.Func([IDL.Text], [IDL.Opt(Trade)], ['query']),
  'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getUniqueTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTrade' : IDL.Func([IDL.Text, TradeInput], [IDL.Opt(Trade)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TradeInput = IDL.Record({
    'result' : IDL.Text,
    'direction' : IDL.Text,
    'timeframe' : IDL.Text,
    'pnlPercent' : IDL.Float64,
    'riskPercent' : IDL.Float64,
    'date' : IDL.Text,
    'psychAfter' : IDL.Vec(IDL.Text),
    'psychBefore' : IDL.Vec(IDL.Text),
    'takeProfit' : IDL.Float64,
    'tags' : IDL.Vec(IDL.Text),
    'movedStopLoss' : IDL.Bool,
    'psychDuring' : IDL.Vec(IDL.Text),
    'entryReason' : IDL.Text,
    'rMultiple' : IDL.Float64,
    'setupGrade' : IDL.Text,
    'rrRatio' : IDL.Float64,
    'session' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'setupType' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'biasBeforeEntry' : IDL.Text,
    'followedRules' : IDL.Bool,
    'exitedEarly' : IDL.Bool,
    'screenshot' : IDL.Opt(ExternalBlob),
    'symbol' : IDL.Text,
    'mainLesson' : IDL.Text,
  });
  const Trade = IDL.Record({
    'id' : IDL.Text,
    'result' : IDL.Text,
    'direction' : IDL.Text,
    'timeframe' : IDL.Text,
    'pnlPercent' : IDL.Float64,
    'riskPercent' : IDL.Float64,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'psychAfter' : IDL.Vec(IDL.Text),
    'psychBefore' : IDL.Vec(IDL.Text),
    'takeProfit' : IDL.Float64,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'movedStopLoss' : IDL.Bool,
    'psychDuring' : IDL.Vec(IDL.Text),
    'entryReason' : IDL.Text,
    'rMultiple' : IDL.Float64,
    'setupGrade' : IDL.Text,
    'updatedAt' : IDL.Int,
    'rrRatio' : IDL.Float64,
    'session' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'setupType' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'biasBeforeEntry' : IDL.Text,
    'followedRules' : IDL.Bool,
    'exitedEarly' : IDL.Bool,
    'screenshot' : IDL.Opt(ExternalBlob),
    'symbol' : IDL.Text,
    'mainLesson' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'totalTrades' : IDL.Nat,
    'avgRR' : IDL.Float64,
    'wins' : IDL.Nat,
    'exitedEarlyPercent' : IDL.Float64,
    'losses' : IDL.Nat,
    'totalNetR' : IDL.Float64,
    'movedStopLossPercent' : IDL.Float64,
    'breakEvens' : IDL.Nat,
    'avgRMultiple' : IDL.Float64,
    'expectancy' : IDL.Float64,
    'winRate' : IDL.Float64,
    'followedRulesPercent' : IDL.Float64,
    'profitFactor' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTrade' : IDL.Func([TradeInput], [Trade], []),
    'deleteTrade' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTradeById' : IDL.Func([IDL.Text], [IDL.Opt(Trade)], ['query']),
    'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getUniqueTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTrade' : IDL.Func([IDL.Text, TradeInput], [IDL.Opt(Trade)], []),
  });
};

export const init = ({ IDL }) => { return []; };