/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface Drill {
    id: string;
    marketShiftObservations: string;
    liquidityObservations: string;
    timeframe: string;
    entryAnalysis: string;
    owner: Principal;
    date: string;
    createdAt: bigint;
    structureNotes: string;
    drillType: string;
    updatedAt: bigint;
    induceNotes: string;
    screenshot?: ExternalBlob;
    symbol: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Trade {
    id: string;
    result: string;
    direction: string;
    timeframe: string;
    pnlPercent: number;
    riskPercent: number;
    owner: Principal;
    date: string;
    psychAfter: Array<string>;
    psychBefore: Array<string>;
    takeProfit: number;
    createdAt: bigint;
    tags: Array<string>;
    movedStopLoss: boolean;
    psychDuring: Array<string>;
    entryReason: string;
    rMultiple: number;
    accountBalance: number;
    setupGrade: string;
    updatedAt: bigint;
    rrRatio: number;
    session: string;
    stopLoss: number;
    setupType: string;
    entryPrice: number;
    biasBeforeEntry: string;
    followedRules: boolean;
    exitedEarly: boolean;
    pnlDollar: number;
    screenshot?: ExternalBlob;
    symbol: string;
    mainLesson: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TradeSegment {
    totalTrades: bigint;
    avgRR: number;
    segmentLabel: string;
    winRate: number;
}
export interface DrillInput {
    marketShiftObservations: string;
    liquidityObservations: string;
    timeframe: string;
    entryAnalysis: string;
    date: string;
    structureNotes: string;
    drillType: string;
    induceNotes: string;
    screenshot?: ExternalBlob;
    symbol: string;
}
export interface ExtendedAnalytics {
    totalTrades: bigint;
    avgRR: number;
    tradeSegments: Array<TradeSegment>;
    wins: bigint;
    exitedEarlyPercent: number;
    losses: bigint;
    totalNetR: number;
    avgLoss: number;
    sortedRMultiples: Array<number>;
    movedStopLossPercent: number;
    breakEvens: bigint;
    avgRMultiple: number;
    expectancy: number;
    winRate: number;
    followedRulesPercent: number;
    profitFactor: number;
    avgWin: number;
}
export interface Analytics {
    totalTrades: bigint;
    avgRR: number;
    wins: bigint;
    exitedEarlyPercent: number;
    losses: bigint;
    totalNetR: number;
    movedStopLossPercent: number;
    breakEvens: bigint;
    avgRMultiple: number;
    expectancy: number;
    winRate: number;
    followedRulesPercent: number;
    profitFactor: number;
}
export interface TradeInput {
    result: string;
    direction: string;
    timeframe: string;
    pnlPercent: number;
    riskPercent: number;
    date: string;
    psychAfter: Array<string>;
    psychBefore: Array<string>;
    takeProfit: number;
    tags: Array<string>;
    movedStopLoss: boolean;
    psychDuring: Array<string>;
    entryReason: string;
    rMultiple: number;
    accountBalance: number;
    setupGrade: string;
    rrRatio: number;
    session: string;
    stopLoss: number;
    setupType: string;
    entryPrice: number;
    biasBeforeEntry: string;
    followedRules: boolean;
    exitedEarly: boolean;
    pnlDollar: number;
    screenshot?: ExternalBlob;
    symbol: string;
    mainLesson: string;
}
export interface PlatformStats {
    totalTrades: bigint;
    totalUsersWithTrades: bigint;
    avgWinRate: number;
    mostActiveTrader: Principal;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserStats {
    totalTrades: bigint;
    avgRR: number;
    owner: Principal;
    wins: bigint;
    losses: bigint;
    totalNetR: number;
    avgRMultiple: number;
    winRate: number;
    mostRecentTradeDate: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface InstitutionalNews {
    id: string;
    institution: string;
    headline: string;
    summary: string;
    currency: string;
    sentiment: string;
    date: string;
    createdAt: bigint;
}
export interface InstitutionalNewsInput {
    institution: string;
    headline: string;
    summary: string;
    currency: string;
    sentiment: string;
    date: string;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminGetAllUsers(): Promise<Array<UserStats>>;
    adminGetPlatformStats(): Promise<PlatformStats>;
    adminGetUserStats(user: Principal): Promise<Analytics>;
    adminGetUserTrades(user: Principal): Promise<Array<Trade>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDrill(input: DrillInput): Promise<Drill>;
    createTrade(input: TradeInput): Promise<Trade>;
    deleteDrill(id: string): Promise<boolean>;
    deleteTrade(id: string): Promise<boolean>;
    getAnalytics(): Promise<Analytics>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDrillById(id: string): Promise<Drill | null>;
    getDrills(): Promise<Array<Drill>>;
    getExtendedAnalytics(): Promise<ExtendedAnalytics>;
    getTradeById(id: string): Promise<Trade | null>;
    getTrades(): Promise<Array<Trade>>;
    createInstitutionalNews(input: InstitutionalNewsInput): Promise<InstitutionalNews>;
    deleteInstitutionalNews(id: string): Promise<boolean>;
    getInstitutionalNews(): Promise<Array<InstitutionalNews>>;
    getUniqueTags(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdminAssigned(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDrill(id: string, input: DrillInput): Promise<Drill | null>;
    updateTrade(id: string, input: TradeInput): Promise<Trade | null>;
}
import type { Drill as _Drill, DrillInput as _DrillInput, ExternalBlob as _ExternalBlob, Trade as _Trade, TradeInput as _TradeInput, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<UserStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return result;
        }
    }
    async adminGetPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPlatformStats();
            return result;
        }
    }
    async adminGetUserStats(arg0: Principal): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserStats(arg0);
            return result;
        }
    }
    async adminGetUserTrades(arg0: Principal): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserTrades(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserTrades(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDrill(arg0: DrillInput): Promise<Drill> {
        if (this.processError) {
            try {
                const result = await this.actor.createDrill(await to_candid_DrillInput_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Drill_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDrill(await to_candid_DrillInput_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Drill_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTrade(arg0: TradeInput): Promise<Trade> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrade(await to_candid_TradeInput_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Trade_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrade(await to_candid_TradeInput_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Trade_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDrill(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDrill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDrill(arg0);
            return result;
        }
    }
    async deleteTrade(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrillById(arg0: string): Promise<Drill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrillById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrillById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrills(): Promise<Array<Drill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrills();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrills();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExtendedAnalytics(): Promise<ExtendedAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getExtendedAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExtendedAnalytics();
            return result;
        }
    }
    async getTradeById(arg0: string): Promise<Trade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeById(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeById(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrades();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrades();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInstitutionalNews(input: InstitutionalNewsInput): Promise<InstitutionalNews> {
        try {
            const result = await this.actor.createInstitutionalNews(input as any);
            return result as unknown as InstitutionalNews;
        } catch (error) {
            if (this.processError) this.processError(error);
            throw error;
        }
    }
    async deleteInstitutionalNews(id: string): Promise<boolean> {
        try {
            const result = await this.actor.deleteInstitutionalNews(id);
            return result;
        } catch (error) {
            if (this.processError) this.processError(error);
            throw error;
        }
    }
    async getInstitutionalNews(): Promise<Array<InstitutionalNews>> {
        try {
            const result = await this.actor.getInstitutionalNews();
            return result as unknown as Array<InstitutionalNews>;
        } catch (error) {
            if (this.processError) this.processError(error);
            throw error;
        }
    }
    async getUniqueTags(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueTags();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminAssigned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminAssigned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminAssigned();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateDrill(arg0: string, arg1: DrillInput): Promise<Drill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDrill(arg0, await to_candid_DrillInput_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDrill(arg0, await to_candid_DrillInput_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrade(arg0: string, arg1: TradeInput): Promise<Trade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(arg0, await to_candid_TradeInput_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(arg0, await to_candid_TradeInput_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_Drill_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Drill): Promise<Drill> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Trade_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Promise<Trade> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Drill]): Promise<Drill | null> {
    return value.length === 0 ? null : await from_candid_Drill_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trade]): Promise<Trade | null> {
    return value.length === 0 ? null : await from_candid_Trade_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    result: string;
    direction: string;
    timeframe: string;
    pnlPercent: number;
    riskPercent: number;
    owner: Principal;
    date: string;
    psychAfter: Array<string>;
    psychBefore: Array<string>;
    takeProfit: number;
    createdAt: bigint;
    tags: Array<string>;
    movedStopLoss: boolean;
    psychDuring: Array<string>;
    entryReason: string;
    rMultiple: number;
    accountBalance: number;
    setupGrade: string;
    updatedAt: bigint;
    rrRatio: number;
    session: string;
    stopLoss: number;
    setupType: string;
    entryPrice: number;
    biasBeforeEntry: string;
    followedRules: boolean;
    exitedEarly: boolean;
    pnlDollar: number;
    screenshot: [] | [_ExternalBlob];
    symbol: string;
    mainLesson: string;
}): Promise<{
    id: string;
    result: string;
    direction: string;
    timeframe: string;
    pnlPercent: number;
    riskPercent: number;
    owner: Principal;
    date: string;
    psychAfter: Array<string>;
    psychBefore: Array<string>;
    takeProfit: number;
    createdAt: bigint;
    tags: Array<string>;
    movedStopLoss: boolean;
    psychDuring: Array<string>;
    entryReason: string;
    rMultiple: number;
    accountBalance: number;
    setupGrade: string;
    updatedAt: bigint;
    rrRatio: number;
    session: string;
    stopLoss: number;
    setupType: string;
    entryPrice: number;
    biasBeforeEntry: string;
    followedRules: boolean;
    exitedEarly: boolean;
    pnlDollar: number;
    screenshot?: ExternalBlob;
    symbol: string;
    mainLesson: string;
}> {
    return {
        id: value.id,
        result: value.result,
        direction: value.direction,
        timeframe: value.timeframe,
        pnlPercent: value.pnlPercent,
        riskPercent: value.riskPercent,
        owner: value.owner,
        date: value.date,
        psychAfter: value.psychAfter,
        psychBefore: value.psychBefore,
        takeProfit: value.takeProfit,
        createdAt: value.createdAt,
        tags: value.tags,
        movedStopLoss: value.movedStopLoss,
        psychDuring: value.psychDuring,
        entryReason: value.entryReason,
        rMultiple: value.rMultiple,
        accountBalance: value.accountBalance,
        setupGrade: value.setupGrade,
        updatedAt: value.updatedAt,
        rrRatio: value.rrRatio,
        session: value.session,
        stopLoss: value.stopLoss,
        setupType: value.setupType,
        entryPrice: value.entryPrice,
        biasBeforeEntry: value.biasBeforeEntry,
        followedRules: value.followedRules,
        exitedEarly: value.exitedEarly,
        pnlDollar: value.pnlDollar,
        screenshot: record_opt_to_undefined(await from_candid_opt_n11(_uploadFile, _downloadFile, value.screenshot)),
        symbol: value.symbol,
        mainLesson: value.mainLesson
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    marketShiftObservations: string;
    liquidityObservations: string;
    timeframe: string;
    entryAnalysis: string;
    owner: Principal;
    date: string;
    createdAt: bigint;
    structureNotes: string;
    drillType: string;
    updatedAt: bigint;
    induceNotes: string;
    screenshot: [] | [_ExternalBlob];
    symbol: string;
}): Promise<{
    id: string;
    marketShiftObservations: string;
    liquidityObservations: string;
    timeframe: string;
    entryAnalysis: string;
    owner: Principal;
    date: string;
    createdAt: bigint;
    structureNotes: string;
    drillType: string;
    updatedAt: bigint;
    induceNotes: string;
    screenshot?: ExternalBlob;
    symbol: string;
}> {
    return {
        id: value.id,
        marketShiftObservations: value.marketShiftObservations,
        liquidityObservations: value.liquidityObservations,
        timeframe: value.timeframe,
        entryAnalysis: value.entryAnalysis,
        owner: value.owner,
        date: value.date,
        createdAt: value.createdAt,
        structureNotes: value.structureNotes,
        drillType: value.drillType,
        updatedAt: value.updatedAt,
        induceNotes: value.induceNotes,
        screenshot: record_opt_to_undefined(await from_candid_opt_n11(_uploadFile, _downloadFile, value.screenshot)),
        symbol: value.symbol
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Drill>): Promise<Array<Drill>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Drill_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Promise<Array<Trade>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Trade_n9(_uploadFile, _downloadFile, x)));
}
async function to_candid_DrillInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrillInput): Promise<_DrillInput> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_TradeInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeInput): Promise<_TradeInput> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketShiftObservations: string;
    liquidityObservations: string;
    timeframe: string;
    entryAnalysis: string;
    date: string;
    structureNotes: string;
    drillType: string;
    induceNotes: string;
    screenshot?: ExternalBlob;
    symbol: string;
}): Promise<{
    marketShiftObservations: string;
    liquidityObservations: string;
    timeframe: string;
    entryAnalysis: string;
    date: string;
    structureNotes: string;
    drillType: string;
    induceNotes: string;
    screenshot: [] | [_ExternalBlob];
    symbol: string;
}> {
    return {
        marketShiftObservations: value.marketShiftObservations,
        liquidityObservations: value.liquidityObservations,
        timeframe: value.timeframe,
        entryAnalysis: value.entryAnalysis,
        date: value.date,
        structureNotes: value.structureNotes,
        drillType: value.drillType,
        induceNotes: value.induceNotes,
        screenshot: value.screenshot ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.screenshot)) : candid_none(),
        symbol: value.symbol
    };
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: string;
    direction: string;
    timeframe: string;
    pnlPercent: number;
    riskPercent: number;
    date: string;
    psychAfter: Array<string>;
    psychBefore: Array<string>;
    takeProfit: number;
    tags: Array<string>;
    movedStopLoss: boolean;
    psychDuring: Array<string>;
    entryReason: string;
    rMultiple: number;
    accountBalance: number;
    setupGrade: string;
    rrRatio: number;
    session: string;
    stopLoss: number;
    setupType: string;
    entryPrice: number;
    biasBeforeEntry: string;
    followedRules: boolean;
    exitedEarly: boolean;
    pnlDollar: number;
    screenshot?: ExternalBlob;
    symbol: string;
    mainLesson: string;
}): Promise<{
    result: string;
    direction: string;
    timeframe: string;
    pnlPercent: number;
    riskPercent: number;
    date: string;
    psychAfter: Array<string>;
    psychBefore: Array<string>;
    takeProfit: number;
    tags: Array<string>;
    movedStopLoss: boolean;
    psychDuring: Array<string>;
    entryReason: string;
    rMultiple: number;
    accountBalance: number;
    setupGrade: string;
    rrRatio: number;
    session: string;
    stopLoss: number;
    setupType: string;
    entryPrice: number;
    biasBeforeEntry: string;
    followedRules: boolean;
    exitedEarly: boolean;
    pnlDollar: number;
    screenshot: [] | [_ExternalBlob];
    symbol: string;
    mainLesson: string;
}> {
    return {
        result: value.result,
        direction: value.direction,
        timeframe: value.timeframe,
        pnlPercent: value.pnlPercent,
        riskPercent: value.riskPercent,
        date: value.date,
        psychAfter: value.psychAfter,
        psychBefore: value.psychBefore,
        takeProfit: value.takeProfit,
        tags: value.tags,
        movedStopLoss: value.movedStopLoss,
        psychDuring: value.psychDuring,
        entryReason: value.entryReason,
        rMultiple: value.rMultiple,
        accountBalance: value.accountBalance,
        setupGrade: value.setupGrade,
        rrRatio: value.rrRatio,
        session: value.session,
        stopLoss: value.stopLoss,
        setupType: value.setupType,
        entryPrice: value.entryPrice,
        biasBeforeEntry: value.biasBeforeEntry,
        followedRules: value.followedRules,
        exitedEarly: value.exitedEarly,
        pnlDollar: value.pnlDollar,
        screenshot: value.screenshot ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.screenshot)) : candid_none(),
        symbol: value.symbol,
        mainLesson: value.mainLesson
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
